### ISSUE TITLE
make a search bar in interactive hardware doc

### ISSUE THREAD

**Issue by qgeissmann** [sticky-pi/sticky-pi.github.io#7]
A simple search bar that finds `#` using keywords from the name/description.

**Comment by WeiXie03** [comment]
some options for search libraries:
- [list.js](https://listjs.com/), [data/custom attributes](https://listjs.com/examples/data-attributes-custom-attributes/), [fuzzy search](https://listjs.com/examples/fuzzy-search/)
- [fuse.js](https://fusejs.io/), a little more work (front end--search bar, autocomplete dropdown, showing results, etc.)

**Comment by WeiXie03** [comment]
using [easyAutocomplete](http://easyautocomplete.com/),
made small example: searching parts and processes by name with autocomplete, little icon beside results to indicate part/proc
